### ISSUE TITLE
Crash VoiceRange Addon

### ISSUE THREAD

**Issue by HeberonYT** [ZeEvoker2Vex/Z-VoiceRange-Addon#1]
Salut. Merci d'avoir développé cet addon, il est très utile pour les serveurs RP.
Lors de la déconnexion de mon serveur et de la sortie du menu principal, mon jeu plante.
Ceci est le rapport de problème. Les salutations!

https://pastebin.com/raw/J1yZjWNF

version: Z-VoiceRange-1.12.2-1.0.0.jar

**Comment by SeedenDev** [comment]
Bonjour !
Merci pour ce report.
Cependant serait-t-il possible d'obtenir les logs du serveur au moment du crash s'il vous plaît ?

Si vous le souhaitez, vous pouvez me les envoyer via Discord : ZeEvoker2Vex#3936

**Comment by SeedenDev** [comment]
Normalement le problème est réglé dans la nouvelle version :
=> https://github.com/ZeEvoker2Vex/Z-VoiceRange-Addon/releases/tag/1.0.1

Merci de me le confirmer ici pour clore l'issue ^^
Même si le problème ne se produit pas toujours, je pense qu'au bout de quelques tests cela pourrait être concluant :D

Cordialement, ZeEvoker2Vex.
